name: Chore
description: Tooling, docs, maintenance
title: "[Chore] "
labels: ["type:chore"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What needs to be done?
    validations:
      required: true
  - type: textarea
    id: scope
    attributes:
      label: Scope
      description: In scope and out of scope
      placeholder: "- In scope: ...\n- Out of scope: ..."
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      placeholder: "- [ ] ..."
